stateDiagram-v2
  [*] --> QUERY_IDLE
  QUERY_IDLE --> QUERY_RD_WRPTR_ADDR: write MCQD table addr/mask
  QUERY_RD_WRPTR_ADDR --> QUERY_RD_WRPTR_VALUE
  QUERY_RD_WRPTR_VALUE --> QUERY_RD_ADDR_WAIT
  QUERY_RD_ADDR_WAIT --> QUERY_IDLE
