stateDiagram-v2
  [*] --> HCQD_IDLE
  HCQD_IDLE --> HCQD_READ_MCQD: write MCQD_ADDR/BINDDMA_HCQDID
  HCQD_READ_MCQD --> HCQD_READ_RPWP
  HCQD_READ_RPWP --> HCQD_WAIT_MCQD
  HCQD_WAIT_MCQD --> HCQD_WAIT_BRSP
  HCQD_WAIT_BRSP --> HCQD_WAIT_RPWP
  HCQD_WAIT_RPWP --> HCQD_BIND_HCQD
  HCQD_BIND_HCQD --> HCQD_IDLE
